<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>_2faConsole</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Pxoqxo.ConsolePlus">
      <HintPath>..\..\publish\Pxoqxo.ConsolePlus\em1.0\portable\Pxoqxo.ConsolePlus.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
