<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>_2faConsole</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Pxoqxo.ConsolePlus">
      <HintPath>..\..\publish\Pxoqxo.ConsolePlus\em1.0\portable\Pxoqxo.ConsolePlus.dll</HintPath>
    </Reference>
    <Reference Include="Pxoqxo.Ext.Core">
      <HintPath>..\..\publish\Pxoqxo.Ext\em1.0\portable\Pxoqxo.Ext.Core.dll</HintPath>
    </Reference>
    <Reference Include="Pxoqxo.Otp2fa">
      <HintPath>..\..\publish\Pxoqxo.Otp2fa\em1.0\portable\Pxoqxo.Otp2fa.dll</HintPath>
    </Reference>
    <Reference Include="Pxoqxo.Quick">
      <HintPath>..\..\publish\Pxoqxo.Quick\em1.0\portable\Pxoqxo.Quick.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
